### ISSUE TITLE
Invalid argument(s): Failed to lookup symbol 'native_add': dlsym(RTLD_DEFAULT, native_add): symbol not found

### ISSUE THREAD

**Issue by wuwenju** [ipcjs/g711_flutter#1]
help，the symbol not found，

**Comment by ipcjs** [comment]
What is your flutter version?

android or iOS?

**Comment by ipcjs** [comment]
啥系统？iOS还是Android？试过[DartG711Codec](https://github.com/ipcjs/g711_flutter/blob/master/lib/src/dart_g711.dart)吗？
